[package]
name = "server"
version = "0.1.0"
authors = ["Sondre Russvoll <sondre@russvoll.no>"]

[dependencies]
futures = "0.1.14"
hyper = "0.11.2"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
tokio = "0.1.1"
tokio-io = "0.1"
bytes = "0.4.6"
csv = "1.0.0-beta.5"
byteorder = "1.2.1"